secret_key = 'bezbozhiye botforty vyvernutsya doslushat kibernetik predrassudok protivoyadiye raskrovenit slyapat'
img_dir = r'static/img'
img_to_save_dir = r'static/img_to_save'
pdf_dir = r'static/pdf'
svg_for_pdf_dir = r'static/svg_for_pdf'
svg_zip_dir = r'static/svg_zip_to_save'
